### ISSUE TITLE
2 Factor Support..

### ISSUE THREAD

**Issue by th3nolo** [ifedapoolarewaju/igdm#1087] opened 2019-09-23 21:03 UTC
I just want to have.. 2 Factor Authh.. support.

**Comment by belaarany** [comment] 2019-10-02 08:29
Duplicate of #982

**Comment by ifedapoolarewaju** [comment] 2019-10-02 08:31
closing as duplicate (@belaarany thank you for the hint)

**Closed by ifedapoolarewaju** 2019-10-02 08:31 UTC
