### ISSUE TITLE
Instagram call checkpoint for this action!

### ISSUE THREAD

**Issue by alice1232** [ifedapoolarewaju/igdm#150] opened 2018-04-19 12:31 UTC
My instagram DMs won't work at all and its pretty annoying to me

**Comment by shrenika-solanki** [comment] 2018-04-19 13:31
same here how to fix this problem

**Comment by alejoloaiza** [comment] 2018-04-21 14:36
same here "Instagram call checkpoint for this action!"

**Comment by chadleylyell** [comment] 2018-04-24 01:32
Is it possible that your guys' accounts got locked by Instagram?

**Comment by alexmozzhakov** [comment] 2018-04-25 07:08
Duplicate of #125

**Comment by alexmozzhakov** [comment] 2018-04-25 07:09
@chadleylyell that's not an issue here

**Comment by MirzaUmar3211** [comment] 2018-08-16 09:38
Instagram call checkpoint for this action!
Plz solve my problem

**Comment by cameronmck2000** [comment] 2018-08-23 15:27
Found the problem, you need to go onto the instagram website because someone tried to log into your account and it put it in a checkpoint, causing this problem, all you need to do is change your password or say yes it was me when it asks you.

**Closed** 2018-09-22 07:36 UTC

**Comment by Avatar4pro** [comment] 2019-02-21 15:40
turn off 2f auth.
