### ISSUE TITLE
Not opening on my windows

### ISSUE THREAD

**Issue by chinnatron** [ifedapoolarewaju/igdm#42] opened 2017-11-23 21:35 UTC
When i run the igdm setup, it asks me if i want to run it and i click "run". then nothing happens after that.

**Comment by ifedapoolarewaju** [comment] 2017-11-24 07:24
This is a weird behavior, could you try downloading the setup again from the website again and restarting your system before trying a fresh installation?

**Comment by salvatorefoderaro** [comment] 2017-11-26 20:55
Same problem here. Last Windows 10 CU. If I try to run it in "Compatibility mode" I can get the installer windows but after that crashes. Just tried redownload and system's restart

**Comment by ifedapoolarewaju** [comment] 2018-02-04 19:46
closing this as a duplicate of https://github.com/ifedapoolarewaju/igdm/issues/52

**Closed by ifedapoolarewaju** 2018-02-04 19:46 UTC
