### ISSUE TITLE
No message history

### ISSUE THREAD

**Issue by acsbendi** [ifedapoolarewaju/igdm#39] opened 2017-11-17 16:27 UTC
I can only view the last 10 messages or so. It would be very useful to see older messages as well. 
Thank you for the app:)

**Comment by ifedapoolarewaju** [comment] 2017-12-04 20:47
closing this as duplicate of this https://github.com/ifedapoolarewaju/igdm/issues/13

**Closed by ifedapoolarewaju** 2017-12-04 20:47 UTC
