### ISSUE TITLE
Can't remember login

### ISSUE THREAD

**Issue by XexuWilder** [ifedapoolarewaju/igdm#105] opened 2018-03-12 19:36 UTC
The app can't remember the login data.

You have to write your credentials everytime the app opens

**Comment by ifedapoolarewaju** [comment] 2018-03-12 23:50
@XexuWilder are you running it on a linux machine? If so please download this version https://github.com/ifedapoolarewaju/igdm/releases/download/v2.3.1/IGdm-2.3.1-x86_64.AppImage

**Comment by ifedapoolarewaju** [comment] 2018-03-25 00:50
closing this because I can't reproduce, and I'm not getting a response

**Closed by ifedapoolarewaju** 2018-03-25 00:50 UTC
