### ISSUE TITLE
Unable to Install in WIN 7

### ISSUE THREAD

**Issue by Rokuh** [ifedapoolarewaju/igdm#79] opened 2018-02-03 19:27 UTC
The setup doesn't start in WIN 7 at all. Keeps throwing this again and again...

![2313121](https://user-images.githubusercontent.com/36113195/35770708-4a404bc8-0946-11e8-8702-6fa710886fa6.png)

Any help?

**Comment by ifedapoolarewaju** [comment] 2018-02-04 19:41
closing as duplicate of this https://github.com/ifedapoolarewaju/igdm/issues/52

**Closed by ifedapoolarewaju** 2018-02-04 19:41 UTC
