### ISSUE TITLE
Instagram call checkpoint for this action!

### ISSUE THREAD

**Issue by ninabui2005** [ifedapoolarewaju/igdm#88] opened 2018-02-11 12:16 UTC
when i try signing in, it keeps saying Instagram call checkpoint for this action! and then when i keep pressing it many times, it says Please wait a few minutes before you try again.

**Comment by udiudiudiudi** [comment] 2018-02-12 20:39
if you are on wifi, with the computer and mobile on wifi, then no checkpoint

**Comment by alexmozzhakov** [comment] 2018-04-25 07:12
Duplicate of #60

**Closed** 2018-09-22 07:36 UTC
