### ISSUE TITLE
IG FOR DESKTOP

### ISSUE THREAD

**Issue by shane6** [ifedapoolarewaju/igdm#65] opened 2018-01-15 21:04 UTC
what does "Error Socket Hang Up" mean on the desktop for ig dms on  the log in screen and how do i fix it?

**Comment by ifedapoolarewaju** [comment] 2018-02-04 19:37
closing as duplicate of https://github.com/ifedapoolarewaju/igdm/issues/64

**Closed by ifedapoolarewaju** 2018-02-04 19:37 UTC
