### ISSUE TITLE
I CAN NOT LOG IN THE APPLICATION: "Checkpoint issue"

### ISSUE THREAD

**Issue by KaddishSaint** [ifedapoolarewaju/igdm#113] opened 2018-03-24 05:25 UTC
Good night guys.

I just can not log in to the program, I always get the following message: "Instagram call checkpoint for this action!". From this, when at the official Instagram web he brings me the following message "We detected an unusual login attempt" and asks me to confirm if it was me that I tried to access. When I confirm and try to log back into "IGDM", the same checkpoint problem happens, in an infinite and unresolved cycle (prints below). The computer and smartphone are always logged on to the same network.

I'm looking for help, feelas. Thanks for listening!

Have a good weekend!

![clipimage](https://user-images.githubusercontent.com/32812099/37860714-462953ec-2f0a-11e8-9669-0ef916908092.jpg)
![clipimage](https://user-images.githubusercontent.com/32812099/37860716-4fdfd8f2-2f0a-11e8-8a08-89b5d62155d7.jpg)

**Comment by alexmozzhakov** [comment] 2018-04-25 07:11
Duplicate of #60

**Closed** 2018-09-22 07:36 UTC
