### ISSUE TITLE
There are only 20 messages I can read.

### ISSUE THREAD

**Issue by iwolfmarketing** [ifedapoolarewaju/igdm#62] opened 2018-01-13 14:19 UTC
Why does IGDM cannot load more than 20 messages in a conversation?

**Comment by ifedapoolarewaju** [comment] 2018-03-25 01:10
closing this as duplicate of this https://github.com/ifedapoolarewaju/igdm/issues/89

**Closed by ifedapoolarewaju** 2018-03-25 01:10 UTC
