### ISSUE TITLE
Cannot Vertically Resize window

### ISSUE THREAD

**Issue by sibaar** [ifedapoolarewaju/igdm#74] opened 2018-01-29 05:20 UTC
Window is too large and cannot resize vertically but horizontal resize is functional. 
Running 2.3.1 on Ubuntu 17.10

**Comment by ifedapoolarewaju** [comment] 2018-02-04 19:32
closing this as duplicate of this https://github.com/ifedapoolarewaju/igdm/issues/45

**Closed by ifedapoolarewaju** 2018-02-04 19:32 UTC
Labels: done
