### ISSUE TITLE
Can't send photos

### ISSUE THREAD

**Issue by princepathria** [ifedapoolarewaju/igdm#43] opened 2017-11-25 08:14 UTC
Please add this feature

**Comment by sibaar** [comment] 2017-12-02 07:52
Too vague! Might want to include more information. More details the better.

example: platform, version, specific problem and how to recreate it.

**Comment by ifedapoolarewaju** [comment] 2017-12-04 00:58
closing this because it is a duplicate of this one https://github.com/ifedapoolarewaju/igdm/issues/3

**Closed by ifedapoolarewaju** 2017-12-04 00:58 UTC
