### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by Meeraalmajid** [ifedapoolarewaju/igdm#102] opened 2018-03-07 13:09 UTC
when I click on windows under the "download the latest v2.3.0" nothing happens it just loads and nothing happens....please help I don't know what to do?

**Comment by ifedapoolarewaju** [comment] 2018-03-11 10:49
it ought to start a download, can you please confirm that this is not an issue with your internet connection?

**Comment by ifedapoolarewaju** [comment] 2018-03-11 10:49
closing because I cannot reproduce this issue, and it is most likely an internet connection issue from your end.

**Closed by ifedapoolarewaju** 2018-03-11 10:49 UTC
