### ISSUE TITLE
can't install 2.3.0 at all

### ISSUE THREAD

**Issue by threenator** [ifedapoolarewaju/igdm#48] opened 2017-12-04 18:19 UTC
When I try to install the new version, the setup closes immediately and I can't install it at all. I'm using Win7.

**Comment by jribbink** [comment] 2018-01-15 02:52
Same...  Im on Win10

**Comment by ifedapoolarewaju** [comment] 2018-02-04 19:44
closing this as a duplicate of this https://github.com/ifedapoolarewaju/igdm/issues/52

**Closed by ifedapoolarewaju** 2018-02-04 19:44 UTC
