### ISSUE TITLE
It have logged me out directly, and now it states Instagram call checkpoint for this action

### ISSUE THREAD

**Issue by CadetYash** [ifedapoolarewaju/igdm#138] opened 2018-04-17 15:11 UTC

**Comment by alejoloaiza** [comment] 2018-04-21 14:36
same here, getting error "Instagram call checkpoint for this action!" when login

**Comment by alexmozzhakov** [comment] 2018-04-25 07:08
Duplicate of #125

**Comment by ankitmohanbiswas** [comment] 2018-07-20 16:43
what to do

**Closed** 2018-09-22 07:36 UTC
