### ISSUE TITLE
Limited time frame of messages available to access

### ISSUE THREAD

**Issue by inselaffe86** [ifedapoolarewaju/igdm#112] opened 2018-03-21 14:57 UTC
I'm only able to access messages from a limited time period. There's no way to go back further in time beyond the last 25 messages that were received.

**Comment by ifedapoolarewaju** [comment] 2018-03-25 01:07
closing this as a duplicate of this https://github.com/ifedapoolarewaju/igdm/issues/89

**Closed by ifedapoolarewaju** 2018-03-25 01:07 UTC
